services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cognito-auth-app
    volumes:
      - .:/app
      - vendor:/app/vendor
    working_dir: /app
    environment:
      - PHP_VERSION=8.3
    networks:
      - cognito-network
    tty: true
    stdin_open: true

  mysql:
    image: mysql:8.0
    container_name: cognito-auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cognito_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: cognito_user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - cognito-network

networks:
  cognito-network:
    driver: bridge

volumes:
  mysql_data:
  vendor:
